email = "yujiechen0514@gmail.com"
#facebook = "yourfacebookusername"
github = "eugenechen0514"
#gitlab = "yourgitlabusername"
linkedin = "in/yuchieh-chen-37a48989"
#stackoverflow = "yourstackoverflowuserid"
#twitter = "yourtwitterusername"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
#telegram = "yourtelegramusername"
#qq = "yourqqnumber"
#dockerhub = "yourdockerhubusername"
#bitbucket = "yourbitbucketworkspaceid"
medium = "yujiechen0514" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
#bilibili = "yourbilibiliuserid"
